### ISSUE TITLE
Fatal error: exception End_of_file

### ISSUE THREAD

**Issue by jrochel** [dbuenzli/ptime#13]
When compiling anything depending on `ptime` I get the following error:

`ocamlfind: While parsing '$HOME/.opam/4.05.0/lib/ptime/META': Unexpected end of file in line 53 position 1`

I don't see any problem in the `META` file and otherwise have no idea what is going wrong. I can supply more information on my set-up etc, if need be, but maybe the problem is obvious to you at first sight.

**Comment by dbuenzli** [comment]
No. Please post the results of: 

```
opam info ocamlfind ptime -f version
ocamlfind lint $(opam config var ptime:lib)/META
cat $(opam config var ptime:lib)/META
```

**Comment by jrochel** [comment]
> opam info ocamlfind ptime -f version
```
1.7.3-1
0.8.3
```

> ocamlfind lint $(opam config var ptime:lib)/META
```
ocamlfind: Cannot parse '/home/jan/.opam/4.05.0/lib/ptime/META': Unexpected end of file in line 53 position 1
```

> cat $(opam config var ptime:lib)/META
```
description = "POSIX time for OCaml"
version = "0.8.3"
requires = "result"
archive(byte) = "ptime.cma"
archive(native) = "ptime.cmxa"
plugin(byte) = "ptime.cma"
plugin(native) = "ptime.cmxs"

package "top" ( 
  description = "Ptime toplevel support"
  version = "0.8.3"
  requires = "ptime"
  archive(byte) = "ptime_top.cma"
  archive(native) = "ptime_top.cmxa"
  plugin(byte) = "ptime_top.cma"
  plugin(native) = "ptime_top.cmxs"
) 

package "clock" ( 
  description = "POSIX time clocks"
  version = "0.8.3"
  requires = ""

  package "os" ( 
    directory="os"
    description = "Ptime_clock for native OS"
    version = "0.8.3"
    requires = "ptime"
    archive(byte) = "ptime_clock.cma"
    archive(native) = "ptime_clock.cmxa"
    plugin(byte) = "ptime_clock.cma"
    plugin(native) = "ptime_clock.cmxs"

    package "top" ( 
      description = "Ptime_clock native OS toplevel support"
      version = "0.8.3"
      requires = "ptime.top ptime.clock.os"
      archive(byte) = "ptime_clock_top.cma"
      archive(native) = "ptime_clock_top.cmxa"
      plugin(byte) = "ptime_clock_top.cma"
      plugin(native) = "ptime_clock_top.cmxs"

  package "jsoo" ( 
    directory="jsoo"
    description = "Ptime_clock for js_of_ocaml"
    version = "0.8.3"
    requires = "js_of_ocaml ptime"
    archive(byte) = "ptime_clock.cma"
    plugin(byte) = "ptime_clock.cma"
    archive(native) = "ptime_clock.cmxa"
    plugin(native) = "ptime_clock.cmxs"
  )
)
```

Thanks in advance!

**Comment by jrochel** [comment]
I see now that there are two closing parentheses missing.

**Comment by jrochel** [comment]
Problem is resolved. Some script of ours had removed lines containing `exists_if` along with the parentheses. Sorry for the hassle.

**Comment by dbuenzli** [comment]
No problem, but try to reproduce with the public `opam-repository` before. Btw, any particular reason for the existence of that `exists_if` removal ?

**Comment by jrochel** [comment]
The library is used in a docker image which is to be as lean as possible. Therefore we include only the files required for execution which is why we need to remove this check.

**Comment by dbuenzli** [comment]
I'm not sure I understand. The check will precisely make the package unavailable if the mentioned file doesn't exist.

**Comment by jrochel** [comment]
So, in order to save space we don't include any `*.a` and `*.cmxa` files in the docker images as we only need the `*.cmxs` for running the application. But this will lead to the `exists_if` tests to fail, while we KNOW that the library is actually there, including all the files that we need. So, that's why we're fiddling with the META file... I hope I'm being clear this time.

**Comment by dbuenzli** [comment]
Yes thanks !
