### ISSUE TITLE
Round trip conversion to float fails with `max` value

### ISSUE THREAD

**Issue by vbmithr** [dbuenzli/ptime#14]
```ocaml
utop # of_float_s (to_float_s max);;
- : t option = None
```

I don't know if this is an issue or not.

**Comment by dbuenzli** [comment]
This looks like a rounding issue: 

```ocaml
# Ptime.to_float_s Ptime.max;;
- : float = 253402300800.
# Ptime.Span.(to_d_ps @@ match of_float_s 253402300800. with None -> assert false | Some s -> s);;
- : int * int64 = (2932897, 0L)
# Ptime.(Span.to_d_ps @@ to_span Ptime.max);;
- : int * int64 = (2932896, 86399999999999999L)
```

**Comment by vbmithr** [comment]
No, not sure it is a problem for me, either.

**Comment by dbuenzli** [comment]
I don't think I want to get into the rabbit hole of patching floating point rounding errors (e.g. by specialising for `Ptime.max`) however this might warrant a note in the documentation so I'll keep this open for now.

**Comment by cfcs** [comment]
Alternatively lowering `Ptime.max` or removing the floating point thing might make sense?

**Comment by dbuenzli** [comment]
> removing the floating point thing might make sense?

No it doesn't.
