### ISSUE TITLE
Explain Ptime.Span.pp unexpected results in the documentation

### ISSUE THREAD

**Issue by ttamttam** [dbuenzli/ptime#15]
``` caml
utop[31]> Ptime.Span.of_int_s 1 |> Ptime.Span.pp Format.std_formatter;;
1s- : unit = ()
utop[32]> Ptime.Span.of_int_s 30 |> Ptime.Span.pp Format.std_formatter;;
30s- : unit = ()
utop[33]> Ptime.Span.of_int_s 130 |> Ptime.Span.pp Format.std_formatter;;
2min10s- : unit = ()
utop[34]> Ptime.Span.of_int_s 1000 |> Ptime.Span.pp Format.std_formatter;;
16min40s- : unit = ()
utop[35]> Ptime.Span.of_int_s 2000 |> Ptime.Span.pp Format.std_formatter;;
33min20s- : unit = ()
utop[36]> Ptime.Span.of_int_s 3000 |> Ptime.Span.pp Format.std_formatter;;
50min- : unit = ()
utop[37]> Ptime.Span.of_int_s 4000 |> Ptime.Span.pp Format.std_formatter;;
1h7min- : unit = ()
utop[38]> Ptime.Span.of_int_s (4000 - 3600) |> Ptime.Span.pp Format.std_formatter;;
6min40s- : unit = ()
```

I would have expected `Ptime.Span.of_int_s 4000  |> Ptime.Span.pp Format.std_formatter` to print "1h6min40s" instead of "1h7min".

**Comment by dbuenzli** [comment]
Maybe [the documentation](https://github.com/dbuenzli/ptime/blob/12cf82473ab6c3adbb8138e9f7539966cd0d8c6e/src/ptime.mli#L141-L155) should be made more clear that the [implementation](https://github.com/dbuenzli/ptime/blob/master/src/ptime.ml#L297-L302) only prints an approximation of the value. 

Basically once the magnitude is over the hour, the pretty-printer assumes you are not really interested in hearing about seconds which is reasonable in many (but of course not all) pretty-printing scenarios.

**Comment by dbuenzli** [comment]
Note that once you switch to days spans, then it's days-hours, and when you switch to julian years, it's year-day only.

**Comment by ttamttam** [comment]
> Maybe the documentation should be made more clear that the implementation only prints an approximation of the value.

Indeed. I suspected something like that (because of the word "unprecise", and because it can make sense). But after reading Span.pp doc again, I was less convinced that it was the intended behaviour, because it is associated to rounding of very long spans.

With the "approximative" word added (like below), chances are that I would not have bothered you :-) with this question:
> `pp ppf d` prints an unspecified **approximative** representation of `d` on `ppf`.

Thanks for your explanation.

**Comment by dbuenzli** [comment]
> I would not have bothered you :-)

Not bothered ! With the given docstring I agree it's surprising and thanks for the docstring suggestion. I'll add this an maybe a more precise explanation (i.e. two most significant units rounded). 

I also thought about providing maybe the format you wanted, but I think it's a bit out of scope (or say orthogonal) to the lib. Basically you can't provide something that will satisfy all needs here so best would be defining a format string language e.g. along [these lines](https://unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns).
