### ISSUE TITLE
Persisting Ptime.t

### ISSUE THREAD

**Issue by nickbetteridge** [dbuenzli/ptime#16]
I need to break out Ptime.t to an int*int64 so that I can persist t - I'm unable to figure out a way of doing this (even though it's probably staring me in the face!).

Any chance of adding a Ptime.to_d_ps t ?

**Comment by dbuenzli** [comment]
`Ptime.to_span`, should get you started ;-)

**Comment by nickbetteridge** [comment]
Different time zone, different planet. I can now actually observe the slow degradation of cognition. Duh. Thanks!
