### ISSUE TITLE
Bogus-looking check in now()

### ISSUE THREAD

**Issue by novalis** [dbuenzli/ptime#26]
In https://github.com/dbuenzli/ptime/blob/ee061b5d0cb5f091ea80e11374f55285737aca97/src-jsoo/ptime_clock.ml#L34 you check if rem_ms is greater than 86_400_000 -- but rem_ms is ms % 86_400_000, so it should always be less.  Why is that check present?  Should it be removed?

**Comment by dbuenzli** [comment]
Thanks for reading. Very good question, it took me time to figure out again myself :–)

First note that this code is morally equivalent to the one in [`Ptime.Span.of_float_s`](https://github.com/dbuenzli/ptime/blob/ee061b5d0cb5f091ea80e11374f55285737aca97/src/ptime.ml#L142-L152).

This code is just being defensive against potential floating point arithmetic computations inaccuracies in the computation of `rem_ms` when `ms` is negative and very near from a multiple of `86_400_000.`. Not sure if it can really happen but better safe than sorry with floating point numbers.

**Comment by novalis** [comment]
Ocaml `float`s are double precision, so this should not be a problem -- integers up to 2^53 can be stored losslessly, which corresponds to about 8 trillion seconds.

**Comment by dbuenzli** [comment]
The fractional part may still be used.

**Comment by novalis** [comment]
Hm, tricky.  OK, I'll close this since maybe it could happen.

**Comment by dbuenzli** [comment]
I still think it warrants a comment that this is just to guard about a potential overflow. No need to torture our brains about what this could be about (and someone smarter might prove us that this can't happen).

**Comment by dbuenzli** [comment]
> First note that this code is morally equivalent to the one in [`Ptime.Span.of_float_s`](https://github.com/dbuenzli/ptime/blob/ee061b5d0cb5f091ea80e11374f55285737aca97/src/ptime.ml#L142-L152).

Also the code path here could actually overflow (in case that overflow can actually happen).
