### ISSUE TITLE
ptime.1.0 doesn't properly work with dune+js_of_ocaml

### ISSUE THREAD

**Issue by hhugo** [dbuenzli/ptime#28]
The META file installed by ptime is missing an entry to work out of the box with dune.
Without it, dune doesn't understand that ptime comes with a js runtime file when compiling to JS

see https://github.com/dbuenzli/ptime/pull/27

**Comment by dbuenzli** [comment]
I'm sorry don't have the time to go read `dune`'s hard-coded rules for JavaScript. At that time the `js_of_ocaml` project should take the lead an propose a library installation and link standard for libraries that provide need to provide JavaScript stubs. Please stop wasting my time now.

**Comment by dbuenzli** [comment]
> You should stop being grumpy in public.

You should stop saying what people should be in public. I'm sorry for you if you prefer to deal with hypocritical persons.

**Comment by dbuenzli** [comment]
I expect to make a release of `ptime` in the upcoming weeks (say at most end of july). If you want to have a fix for this please provide the instructions.

**Comment by hhugo** [comment]
see https://github.com/ocsigen/js_of_ocaml/pull/1323

**Comment by dbuenzli** [comment]
Thanks !
