### ISSUE TITLE
Breaks esy's sandboxing

### ISSUE THREAD

**Issue by phated** [dbuenzli/ptime#29]
It seems that ptime 1.0.0 breaks esy's sandboxing requirements. I believe ptime is creating files in the sandbox after everything has been copied into the sandbox directory.

We ran into this when trying to build ptime on Windows inside an esy sandbox.

**Comment by dbuenzli** [comment]
I have no idea what you are talking about but:

1. It's unlikely. 
2. You will need to point the precise problem if you want me to investigate anything.

**Comment by phated** [comment]
I don't need you to fix it. I just rip out bad, misbehaving opam deps. Wanted to open the issue so the next person can find the "solution"

**Comment by dbuenzli** [comment]
This issue tracker is for problems with `ptime` itself not for its packaging by third-party package managers. 

Moreover as far as I know the `ptime` opam package is absolutely not misbehaving so I'm not sure what you are talking about here.

**Comment by phated** [comment]
Sorry for taking up your time Daniel. Keep being the perfect person you are 🤗
