### ISSUE TITLE
Day of week

### ISSUE THREAD

**Issue by dinosaure** [dbuenzli/ptime#6]
It's possible to have a convenience function to get the day of week (between 0 and 6) from a date ?

```
val day_of_week : t -> int
```

Or something like that ?

Thanks.

**Comment by dbuenzli** [comment]
`Ptime` is not a calendar library but OTOH his can provide with `Ptime.to_date_time` conversion to other non-normalized standards that are not directly supported by the module. So I may consider. Given the internal representation of the timestamps this is trivial to provide, however I'd rather not use an integer as it's never clear which day is zero (in POSIX, 0 is sunday). 

If you need something immediately something like that should do:
```ocaml
let day_of_week = 
  let wday = [| `Thu; `Fri; `Sat; `Sun; `Mon; `Tue; `Wed |] in (* Epoch was a thursday *)
  fun t -> 
    let i = fst Ptime.(Span.to_d_ps @@ to_span t) mod 7 in 
    wday.(if i < 0 then 7 + i else i)
```

**Comment by dinosaure** [comment]
Thank you for the snippet :+1: !

**Comment by seliopou** [comment]
The day-of-week computation is a more complicated than the one provided above, as it has to take into account leap years. I would be interested in this library providing this functionality, as well as parsing a serialization for the date-time format described in RFC 882 (likely revised in a subsequent RFC).

I could contribute to either or both of these efforts: day of week computation, and parsing/serialization support. Assuming that ptime is portable to non-*NIX platforms, this would be used by [webmachine](https://github.com/inhabitedtype/ocaml-webmachine) to generate and parse conditional request headers.

**Comment by dbuenzli** [comment]
> The day-of-week computation is a more complicated than the one provided above, as it has to take into account leap years.

I don't think this is the case, please provide a counter example.

**Comment by dbuenzli** [comment]
Note before trying to find one you may want to have a close look what was done here... https://github.com/mirage/mirage-clock/pull/2

**Comment by seliopou** [comment]
Ah, the code already accounts for that. Got it.

**Comment by Chris00** [comment]
I understand that Ptime is not a calendar library and that `day_of_week` is simple to implement but I think it is bound to be rewritten by many users so supporting it in the library would make sense.  Alternatively, a calendar library based on Ptime would also be nice... ☺
